### ISSUE TITLE
JB2008 Indices 403

### ISSUE THREAD

**Issue by xlxs4** [JuliaSpace/SpaceIndices.jl#5]
http://sol.spacenvironment.net/jb2008/indices/DTCFILE.TXT was changed and it seems that a token is now needed for access (obtained automatically by navigating through https://spacewx.com/jb2008/), e.g. `https://sol.spacenvironment.net/JB2008/index.php?token=e54e295b-4db3-4db4-9be6-3438501b7dc0&state=1641180456`.

Been getting `ERROR: RequestError: HTTP/1.1 403 Forbidden while requesting http://sol.spacenvironment.net/jb2008/indices/DTCFILE.TXT` errors from `SpaceIndices.init()` for a while now

**Comment by patelraj425** [comment]
I am having the same issue. Capitalizing JB2008 in the url such that `http://sol.spacenvironment.net/jb2008/indices/DTCFILE.TXT ` becomes `http://sol.spacenvironment.net/JB2008/indices/DTCFILE.TXT ` allows access to the files. Need this change in the source code for it to work with `SpaceIndices.init()`

**Comment by ronisbr** [comment]
Hi!

Thanks for the report @xlxs4.

Indeed, if we capitalize `JB2008` everything works. I have no ideia why this happens since everything is supposed to be case invariant :) I think it is the first time I see something like this. I will commit a fix and tag a new release now. Thanks @patelraj425 for the information!
